"""Global test fixtures for the Sourdough Monitor integration."""

from custom_components.sourdough.const import (
    CONF_DISCARD_RATIO,
    CONF_FLOUR_AMOUNT,
    CONF_UNIT_SYSTEM,
    CONF_VESSEL_TARE,
    CONF_WATER_AMOUNT,
    DEFAULT_DISCARD_RATIO,
    DEFAULT_FLOUR_GRAMS,
    DEFAULT_VESSEL_TARE_GRAMS,
    DEFAULT_WATER_GRAMS,
    UNIT_METRIC,
)

DEFAULT_CONFIG = {
    CONF_UNIT_SYSTEM: UNIT_METRIC,
    CONF_FLOUR_AMOUNT: DEFAULT_FLOUR_GRAMS,
    CONF_WATER_AMOUNT: DEFAULT_WATER_GRAMS,
    CONF_VESSEL_TARE: DEFAULT_VESSEL_TARE_GRAMS,
    CONF_DISCARD_RATIO: DEFAULT_DISCARD_RATIO,
}
